language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
node_js:
- '8'
- '10'
deploy:
  provider: npm
  email: hatatatehaze@gmail.com
  api_key:
    secure: 1QyT2yxV92LaBfmoMSFZyO9zbUjHG8DYdu57SHOBevkyCb6MwnBjpqDw9ep+DCEqJza82gUZ+lZuT48SBkHaR4hFnyAd2/O2HFRQ/jBOnGY6M2lZlwvD7oeV9ze2mUWh2VBOuAQcZfdnF9qNqR9bCCs5D8Bvn9/Z6LyCZ/X+H0v3ENTH50RUHsQideeI0sBJ12PJk16jnlxovxPlIMYv5oukNGDtOnU6JmdzqVl69ocH30DF7us++SmgcTJp/KQxYdrsWBNTLxPvIlNSA3rE4xmylBUMI63XJ7xXHdfbV2YjS+feGAq4RuPrGJhf1wJmnStH1R9mJBNYc8TrWVnst+yGmijOm+p5LL67k5RY3DL45WQ6UfZI/AJiohPDyRoAt98jgnAmBcsuo1Zd45N/AZ5eDWMF0gRneZe2wTYcohFxP3DQ9irm+qPnSzmqfyGhbFSSLqS0GWA9+Bk0GVL9OHACLxes+XCYRcq2mCM+3QAjQkbmif9nNRI/K8F2MRHbb8p3DUKHLY82ObGjM8OSJ2YWM0ebf7N5F6k5jnjQQJjWny0fFM4bdiBbonz1ifs0xj3qKWYJ2GHpqG5kok7MU1nCCw3D2VroOc6wtv/8jiPEvY44uBrh9BpmARgQvaSfdNsOkF4hVxL6RlMzQTM5yf9cTBME4BJFAZjuA2pHoCU=
  on:
    branch: master
    tags: true
    repo: tilecloud/mbgl-japanese-prefs
  skip_cleanup: true
